# Generated by Django 6.0.7 on 2026-08-10 08:37

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='card_code',
            field=models.CharField(default=store.models.generate_16_digit_card_code, max_length=50, unique=True),
        ),
    ]
