# Generated by Django 6.0.7 on 2026-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'COD'), ('O', 'Online'), ('B', 'bKash'), ('N', 'Nagad')], default='C', max_length=1),
        ),
    ]
