# Generated by Django 6.0.7 on 2026-08-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_phone_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
