# Generated by Django 6.0.7 on 2026-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_transaction_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vibe_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
