# Generated by Django 6.0.7 on 2026-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_customer_vibe_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'COD'), ('O', 'Online'), ('B', 'bKash'), ('N', 'Nagad'), ('V', 'VibeCoin')], default='C', max_length=1),
        ),
    ]
