# Generated by Django 6.0.7 on 2026-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vibe_coin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
