# Generated by Django 6.0.7 on 2026-08-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_customer_vibe_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_photos_published',
            field=models.BooleanField(default=True),
        ),
    ]
