# Generated by Django 6.0.7 on 2026-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_is_photos_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
