# Generated by Django 6.0.7 on 2026-08-16 06:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_discount_percent_promotion_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(default=store.models.default_coupon_expiry)),
                ('target_type', models.CharField(choices=[('product', 'Specific Products'), ('collection', 'Collection')], default='product', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='store.collection')),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
