# Generated by Django 6.0.7 on 2026-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Short Description'),
        ),
    ]
