# Generated by Django 6.0.7 on 2026-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_orderitem_variant_title_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(default='01711111111', max_length=20)),
                ('bkash_active', models.BooleanField(default=True)),
                ('nagad_number', models.CharField(default='01711111111', max_length=20)),
                ('nagad_active', models.BooleanField(default=True)),
                ('cod_active', models.BooleanField(default=True)),
                ('vibecoin_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
