# Generated by Django 6.0.7 on 2026-08-18 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_dhaka_charge', models.DecimalField(decimal_places=2, default=60.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('outside_dhaka_charge', models.DecimalField(decimal_places=2, default=130.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days_inside', models.CharField(blank=True, default='1-2 Days', max_length=50)),
                ('estimated_days_outside', models.CharField(blank=True, default='3-5 Days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(choices=[('inside_dhaka', 'Inside Dhaka'), ('outside_dhaka', 'Outside Dhaka')], default='inside_dhaka', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
