# Generated by Django 6.0.7 on 2026-08-18 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_deliverysetting_order_delivery_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysetting',
            name='inside_dhaka_charge',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='outside_dhaka_charge',
            field=models.DecimalField(decimal_places=2, default=130.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
