# Generated by Django 6.0.7 on 2026-08-18 04:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_deliverysetting_inside_dhaka_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('product', 'Specific Products'), ('collection', 'Collection')], default='product', max_length=20)),
                ('rule_type', models.CharField(choices=[('free', 'Free Delivery (৳0)'), ('reduced', 'Reduced Delivery Charge')], default='free', max_length=20)),
                ('inside_dhaka_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('outside_dhaka_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_rules', to='store.collection')),
                ('products', models.ManyToManyField(blank=True, related_name='delivery_rules', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
