# Generated by Django 6.0.7 on 2026-08-18 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_deliveryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrule',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
