# Generated by Django 6.0.7 on 2026-08-25 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrule',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='target_type',
            field=models.CharField(choices=[('product', 'Specific Products'), ('collection', 'Collection'), ('order_total', 'Order Total / Cart Amount Threshold')], default='product', max_length=20),
        ),
    ]
