# Generated by Django 6.0.7 on 2026-08-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_edited_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
