# Generated by Django 6.0.7 on 2026-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_order_edited_at_order_is_edited_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
