# Generated by Django 6.0.7 on 2026-08-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_product_discount_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
