# Generated by Django 6.0.7 on 2026-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_promotion_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('stock', 'Low Stock Alert'), ('system', 'System Alert'), ('promotion', 'Promotion Expiry Alert'), ('coupon', 'Coupon Expiry Alert')], default='order', max_length=20),
        ),
    ]
