# Generated by Django 6.0.7 on 2026-09-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='VibeMart', max_length=255)),
                ('tagline', models.CharField(blank=True, default='MAKE-UP STYLE', max_length=255)),
                ('brand_description', models.TextField(blank=True, default='VibeMart is a recognized multi-category fashion and lifestyle store built on the principle of "best price at the highest quality". Our collections are curated with premium materials that are durable, stylish, and perfect for your vibe.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/settings/logos')),
                ('support_phone', models.CharField(blank=True, default='+880 1700-000000', max_length=50)),
                ('support_email', models.EmailField(blank=True, default='support@vibemart.com', max_length=254)),
                ('store_address', models.CharField(blank=True, default='Homestead Gulshan Link Tower, 99 Gulshan Badda Link Rd, Dhaka 1212', max_length=500)),
                ('working_hours', models.CharField(blank=True, default='Sat - Thu: 10:00 - 18:00', max_length=100)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', max_length=500)),
                ('whatsapp_number', models.CharField(blank=True, default='+8801700000000', max_length=50)),
                ('footer_copyright', models.CharField(blank=True, default='© 2026 VIBEMART. ALL RIGHTS RESERVED.', max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
