# Generated by Django 6.0.7 on 2026-09-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='currency_code',
            field=models.CharField(choices=[('BDT', 'BDT (৳) - Bangladeshi Taka'), ('USD', 'USD ($) - US Dollar'), ('EUR', 'EUR (€) - Euro'), ('GBP', 'GBP (£) - British Pound'), ('INR', 'INR (₹) - Indian Rupee'), ('SAR', 'SAR (﷼) - Saudi Riyal'), ('AED', 'AED (د.إ) - UAE Dirham'), ('CAD', 'CAD ($) - Canadian Dollar')], default='BDT', max_length=10),
        ),
    ]
