# Generated by Django 6.0.7 on 2026-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_sitesetting_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('provider_code', models.CharField(choices=[('steadfast', 'Steadfast Courier'), ('pathao', 'Pathao Courier'), ('redx', 'RedX Delivery'), ('paperfly', 'Paperfly'), ('ecourier', 'eCourier'), ('custom', 'Custom / In-House Courier')], default='custom', max_length=30)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=150, null=True)),
                ('base_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tracking_url_template', models.CharField(blank=True, help_text='e.g. https://steadfast.com.bd/t/{tracking_code}', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_inside_dhaka', models.BooleanField(default=False)),
                ('is_default_outside_dhaka', models.BooleanField(default=False)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
