# Generated by Django 6.0.7 on 2026-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_courierprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierprovider',
            name='provider_code',
            field=models.CharField(choices=[('steadfast', 'Steadfast Courier'), ('pathao', 'Pathao Courier'), ('redx', 'RedX Delivery'), ('paperfly', 'Paperfly')], default='steadfast', max_length=30),
        ),
    ]
