# Generated by Django 6.0.7 on 2026-09-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_courierprovider_provider_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_consignment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.courierprovider'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('packed', 'Packed / Ready'), ('in_transit', 'Dispatched / In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned / Failed')], default='pending', max_length=30),
        ),
    ]
