# Generated by Django 6.0.7 on 2026-09-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_order_courier_consignment_id_order_courier_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Return Requested'), ('approved', 'Return Approved / Pickup Scheduled'), ('picked_up', 'Parcel Picked Up'), ('refunded', 'Returned & Refund Completed'), ('rejected', 'Return Rejected'), ('cancelled', 'Cancelled by Customer')], default='pending', max_length=30)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged / Defective Product'), ('wrong_item', 'Wrong Product or Variant Received'), ('not_as_described', 'Item Does Not Match Description'), ('missing_items', 'Missing Items / Accessories'), ('size_fit', 'Size / Fit Issue'), ('other', 'Other Reason')], default='damaged', max_length=50)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('refund_method', models.CharField(choices=[('vibecoin', 'VibeCoin Wallet (Instant Store Credit)'), ('bkash', 'bKash Mobile Banking'), ('nagad', 'Nagad Mobile Banking')], default='vibecoin', max_length=30)),
                ('refund_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('proof_image_1', models.ImageField(blank=True, null=True, upload_to='returns/proofs/')),
                ('proof_image_2', models.ImageField(blank=True, null=True, upload_to='returns/proofs/')),
                ('proof_image_3', models.ImageField(blank=True, null=True, upload_to='returns/proofs/')),
                ('admin_note', models.CharField(blank=True, default='', max_length=1500)),
                ('refund_transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='store.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.returnrequest')),
            ],
        ),
    ]
