# Generated by Django 6.0.7 on 2026-09-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_returnrequest_returnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierprovider',
            name='is_default_inside_dhaka',
        ),
        migrations.RemoveField(
            model_name='courierprovider',
            name='is_default_outside_dhaka',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'New Order'), ('return', 'Return Request'), ('stock', 'Low Stock Alert'), ('system', 'System Alert'), ('promotion', 'Promotion Expiry Alert'), ('coupon', 'Coupon Expiry Alert')], default='order', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Return Requested'), ('approved', 'Return Approved & Pickup Scheduled'), ('picked_up', 'Parcel Picked Up'), ('refunded', 'Returned & Refund Completed'), ('rejected', 'Return Rejected'), ('cancelled', 'Cancelled by Customer')], default='pending', max_length=30),
        ),
    ]
