# Generated by Django 6.0.7 on 2026-09-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_courierprovider_is_default_inside_dhaka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('packed', 'Packed / Ready'), ('in_transit', 'Dispatched / In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned / Failed'), ('cancelled', 'Cancelled by Customer')], default='pending', max_length=30),
        ),
    ]
