# Generated by Django 6.0.7 on 2026-09-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_order_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_1_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.collection'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_1_title',
            field=models.CharField(blank=True, default='LIPSTICKS', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_2_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.collection'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_2_title',
            field=models.CharField(blank=True, default='SKINCARE', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_3_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.collection'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_3_title',
            field=models.CharField(blank=True, default='EYE MAKEUP', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_4_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.collection'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_4_title',
            field=models.CharField(blank=True, default='FOUNDATION & GLOW', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_btn_link',
            field=models.CharField(blank=True, default='/products', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_btn_text',
            field=models.CharField(blank=True, default='View Exclusives', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_subtitle',
            field=models.TextField(blank=True, default='Collect exclusive beauty essentials and immerse yourself in the finest makeup shades.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_title',
            field=models.CharField(blank=True, default='Discover the Glam', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge',
            field=models.CharField(blank=True, default='New Collection', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_btn_link',
            field=models.CharField(blank=True, default='/collections', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_btn_text',
            field=models.CharField(blank=True, default='Explore Collection', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_rotating_words',
            field=models.CharField(blank=True, default='Beauty, Glow, Look, Glam, Charm', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Experience the intersection of luxury cosmetics, skincare, and radiant beauty aesthetics.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_prefix',
            field=models.CharField(blank=True, default='Elevate Your', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/banners/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_banner_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='top_banner_link',
            field=models.CharField(blank=True, default='/gift-cards', max_length=500),
        ),
    ]
