# Generated by Django 6.0.7 on 2026-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_sitesetting_bento_tile_1_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_247_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_247_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/bento/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_delivery_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_delivery_title',
            field=models.CharField(blank=True, default='Fast Delivery', max_length=100),
        ),
    ]
