# Generated by Django 6.0.7 on 2026-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_sitesetting_bento_tile_247_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_247_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
