# Generated by Django 6.0.7 on 2026-09-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_sitesetting_bento_tile_247_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_1_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_247_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_2_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_3_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_4_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bento_tile_delivery_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='brand_description_bn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_btn_text_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_subtitle_bn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='discover_title_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_bn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_btn_text_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_rotating_words_bn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle_bn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title_prefix_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_title_bn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='store_address_bn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline_bn',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours_bn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
