# Generated by Django 6.0.7 on 2026-09-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_sitesetting_bento_tile_1_title_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Meta (Facebook) Pixel ID', max_length=50),
        ),
    ]
