# Generated by Django 6.0.7 on 2026-09-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_sitesetting_meta_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ai_chat_active',
            field=models.BooleanField(default=True, help_text='Enable or disable the AI chat widget storewide'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_active',
            field=models.BooleanField(default=True, help_text='Enable or disable proactive popup bubble on home & product pages'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_delay_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Seconds to wait before popup appears'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_duration_seconds',
            field=models.PositiveIntegerField(default=8, help_text='Seconds the popup stays open before auto-closing'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_home_msg',
            field=models.CharField(blank=True, default="Welcome to VibeMart! Need any shopping help? Let's chat 👋", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_home_msg_bn',
            field=models.CharField(blank=True, default='স্বাগতম VibeMart-এ! কেনাকাটায় কোনো সাহায্য লাগবে? চ্যাট করুন 👋', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_product_msg',
            field=models.CharField(blank=True, default='Any confusion or questions? Just ask me', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ai_nudge_product_msg_bn',
            field=models.CharField(blank=True, default='কোনো প্রশ্ন বা দ্বিধা আছে? আমাকে জিজ্ঞেস করুন!', max_length=250),
        ),
    ]
