# Generated by Django 6.0.7 on 2026-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_sitesetting_ai_chat_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX)', max_length=50),
        ),
    ]
