# Generated by Django 6.0.7 on 2026-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_sitesetting_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='theme_palette',
            field=models.CharField(blank=True, default='botanical_lilac', help_text='Active website color theme palette', max_length=50),
        ),
    ]
