# Generated by Django 6.0.7 on 2026-09-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_sitesetting_theme_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='marquee_is_active',
            field=models.BooleanField(default=True, help_text='Show or hide marquee ticker on homepage'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='marquee_items_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of marquee items {id, text, text_bn, icon, is_active}'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stats_is_active',
            field=models.BooleanField(default=True, help_text='Show or hide live stats counter on homepage'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stats_items_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of stats items {id, target, suffix, prefix, decimals, label, label_bn, sub, sub_bn, icon, is_active}'),
        ),
    ]
