# Generated by Django 6.0.7 on 2026-09-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_sitesetting_marquee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='why_us_is_active',
            field=models.BooleanField(default=True, help_text='Show or hide Why Choose Us section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_us_items_json',
            field=models.TextField(blank=True, default='', help_text='JSON list of Why Choose Us items {id, icon, title, title_bn, desc, desc_bn, is_active}'),
        ),
    ]
