# Generated by Django 6.0.7 on 2026-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_sitesetting_why_us_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, default='', help_text='Google Tag Manager Container ID (e.g. GTM-XXXXXXX)', max_length=50),
        ),
    ]
