# Generated by Django 6.0.7 on 2026-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_sitesetting_google_tag_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='search_rotating_words',
            field=models.CharField(blank=True, default='Skincare Essentials, Lipstick & Lip Gloss, Moisturizing Creams, Organic Hair Care, Serum & Sunscreen', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='search_rotating_words_bn',
            field=models.CharField(blank=True, default='স্কিনকেয়ার প্রোডাক্ট, লিপস্টিক ও মেকআপ, ময়েশ্চারাইজিং ক্রিম, অর্গানিক হেয়ার অয়েল, সিরাম ও সানস্ক্রিন', max_length=500),
        ),
    ]
