# Generated by Django 6.0.6 on 2026-07-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title) 
        VALUES('collection1')
        """,
        """
        DELETE FROM store_collection 
        WHERE title='collection1'
        """
        )
    ]
