from django.core.management.base import BaseCommand
from django.db import connection

class Command(BaseCommand):
    help = 'Fixes missing core_user table and migration history on Render'

    def handle(self, *args, **options):
        with connection.cursor() as cursor:
            # Check if core_user table exists
            cursor.execute("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'core_user');")
            table_exists = cursor.fetchone()[0]

            if not table_exists:
                self.stdout.write("Creating missing core_user table...")
                cursor.execute("""
                    CREATE TABLE core_user (
                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        password varchar(128) NOT NULL,
                        last_login timestamptz NULL,
                        is_superuser boolean NOT NULL,
                        username varchar(150) NOT NULL UNIQUE,
                        first_name varchar(150) NOT NULL,
                        last_name varchar(150) NOT NULL,
                        is_staff boolean NOT NULL,
                        is_active boolean NOT NULL,
                        date_joined timestamptz NOT NULL,
                        email varchar(254) NOT NULL UNIQUE
                    );
                """)
                self.stdout.write(self.style.SUCCESS("Created core_user table successfully."))

            # Ensure core 0001_initial is recorded as applied
            cursor.execute("SELECT id FROM django_migrations WHERE app = 'core' AND name = '0001_initial';")
            if not cursor.fetchone():
                cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES ('core', '0001_initial', NOW());")
                self.stdout.write(self.style.SUCCESS("Recorded core.0001_initial in django_migrations."))

